### ISSUE TITLE
There isn't a `v1.0.0` of cohort-report

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-actions/cohort-report#45]
There isn't a `v1.0.0` of cohort-report, but *README.md* suggests there is:

```yaml
run: cohortreport:v1.0.0 output/input.csv
```

This has tripped up a researcher; I'm sure it will trip up others 🙁 The fix, somewhat surprisingly, isn't to update *README.md* directly. Instead, copy [*.bumpversion.cfg*](https://github.com/opensafely-actions/safetab/blob/main/.bumpversion.cfg) from safetab, changing the `current_version` to the current version of cohort-report. Then commit. Then `make bump`. Don't forget to [update the actions registry](https://github.com/opensafely-core/actions-registry/blob/main/DEVELOPERS.md#updating-the-database), too.

This release process is convoluted, for which I apologize. I asked about automation for reusable actions in [this thread](https://ebmdatalab.slack.com/archives/C63UXGB8E/p1634815245022500), but have yet to implement it.

**Comment by HelenCEBM** [comment]
Is there any reason not to use `latest` most of the time?

**Comment by iaindillingham** [comment]
Yes, the *README.md* is incorrect. `cohort-report` is hyphenated. It would be nice to make *README.md* executable, but I suspect that might be troublesome.

The best reason not to use `latest` is that there isn't a `latest`; using it would raise an error. If there were, a better reason not to use `latest` would be reproducibility. Although there are some complexities, you'd be running the same version of `cohort-report` each time.

**Comment by HelenCEBM** [comment]
Ah OK. We use (or can use) `latest` for (afaik) all other actions though so maybe we should make it really clear in the docs if this one should always be a specified version.

**Comment by HelenCEBM** [comment]
I think people are likely to copy and paste their old studies, other people's, or templates quite often, so it would be handy if there was a warning if a later version is available than the one being used.

**Comment by iaindillingham** [comment]
I'm afraid the other reusable actions don't have `latest` versions either. This is definitely a bug in the documentation! The warning to use the latest version is a great idea. See opensafely-core/job-runner#311.
